[package]
name = "dummy"
version = "0.1.0"
authors = ["lima1909"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "2"
actix-rt = "1"